STRINGS
SET
DICTIONARY
LIST
INTEGER
TUPLE
FLOAT
BOOLEAN

INTRODUCTION TO MACHINE LEARNING WITH PYTHON

In [60]:
MIDE = {"name": "MIDE", "AGE": 14} #dictionary has two notations: keys, values
MIDE = [1, 2, 3, 4] #list
Khan_1 = (1, 1, 2, 4, 5) #tuple
khan2 = 1; #integer
khan_3 = "captain" #string
khan_4 = 5.0 #float
khan_5 = True #boolean
khan_6 = {1, 2, 4, 6} #set
khan_7 = "c-a-p-t"

In [61]:
#To check for the type of an object or variable, use type()
type(khan_6)

set

TYPE CONVERSION / CASTING

In [62]:
type(str(khan2))

str

BASIC OPERATIONS: PEMDAS

In [63]:
a = 5
b = 6
print(a+b) #addition
print(a-b) #subtraction
print(a/b) #division
print(a*b) #multiplication

11
-1
0.8333333333333334
30

Conditional statements & For loop

In [64]:
"""
if type(khan2) != int:
  print ("MIDE IS A GOOD BOY")
else:
  print("MIDE IS A GIRL")
"""

#for loop allows iteration over sequence or list of values/objects
for i in MIDE:
  print(i+2)


#list comprehension

3
4
5
6

LIST COMPREHENSION: ONE OF THE METHODS THAT ENSURES OPTIMIZED MACHINE LEARNING TRAINING

In [65]:
even_number_list = []
odd_number_list = [] # Initialize odd_number_list outside the loop...list is a class- it has attributes and methods, for example append
for i in MIDE:
  if i % 2 ==0:
    even_number_list.append(i)
  else:
    # No need to re-initialize here, it's done once before the loop
    odd_number_list.append(i)

#print(even_number_list)
#print(odd_number_list)

#LIST COMPREHENSION
even_number_list = [i for i in MIDE if i % 2 == 0]
odd_number_list = [i for i in MIDE if i % 2 != 0]

print(even_number_list)
print(odd_number_list)

[2, 4]
[1, 3]

BRIEF: OBJECT ORIENTED PROGRAMMING

In [66]:
khan_7 = "c-a-p-t"
print(khan_7.split("-"))

['c', 'a', 'p', 't']

In [67]:
#define a function
def AREA(l, h=50):
  #L = LENGTH
  #H = HEIGHT
  return l*h

AREA(2, h = 100)

200

In [68]:
class Swep():
  def __init__(self, uni, level, dept, count = 47): #number of students = 47
    self.uni = uni
    self.level = level
    self.dept = dept
    self.count = count

  def product_of_student_count_with_length_of_uni(self): #method, belongs to class
    product = self.count * self.level
    return product

uni = "OAU"
level = 250
dept = "CHE"

#STEP1: INITIALIZE THE CLASS
swep = Swep(uni, level, dept)

#step2: PERFORM THE ACTION: to perform an operation under a clas, use the dot notation, for example initialie class.method)
swep.product_of_student_count_with_length_of_uni()

11750

LOADING A DATASET WITH PYTHON USING PANDA

In [69]:
import pandas as pd
"""
panda is a python library used for loading datasets, andd performing exploratory data analysis, which include data preprocessing,
data-transformation, data wrangling, etc.
"""

#load the dataset
df = pd.read_csv("/content/AI_SocialMedia_Student_Dataset.csv")
df

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04
...,...,...,...,...,...,...,...,...,...,...
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

.head():by default, returns the first five rowms.tail():by default, returns the last 5 rows.info():provide the summary of the dataset
.desceibe():provides the statistical summary of the dataset

In [70]:
df.head()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [71]:
df.tail()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 16000 non-null  object
 1   Age                        16000 non-null  int64
 2   Gender                     16000 non-null  object
 3   Education_Level            16000 non-null  object
 4   Daily_Social_Media_Hours   16000 non-null  float64
 5   Daily_AI_Tool_Usage_Hours  16000 non-null  float64
 6   Sleep_Hours                16000 non-null  float64
 7   Physical_Activity_Hours    16000 non-null  float64
 8   Mental_Health_Score        16000 non-null  float64
 9   Physical_Health_Score      16000 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 1.2+ MB

In [73]:
df["Gender"].dtype

dtype('O')

In [74]:
df.drop("Student_ID", axis=1, inplace=True) #setting axis to 1 means points to columns

In [75]:
df.to_csv("swep.csv", index=False)